import { StyleSheet } from 'react-native';
import { useTheme } from '../context/ThemeContext';

export const appColors = {
  white: '#FFFFFF',
  black: '#000000',
  background: '#0B0E14',
  surface: 'rgba(255,255,255,0.06)',
  border: 'rgba(255,255,255,0.10)',
  primary: '#B4F736',
  primaryText: '#111827',
  textPrimary: '#F9FAFB',
  textSecondary: '#9CA3AF',
  error: '#FF4B4B',
};

export const radii = {
  sm: 8,
  md: 16,
  lg: 20,
  xl: 24,
  full: 999,
};

export const appStyles = StyleSheet.create({
  forgotText: {
    color: appColors.textSecondary,
    textAlign: 'center',
    fontSize: 14,
    letterSpacing: 0.5,
    fontFamily: 'Inter_400Regular',
  },
  screen: {
    flex: 1,
    paddingHorizontal: 28,
    paddingVertical: 12,
    backgroundColor: appColors.background,
    gap: 22,
  },
  screenContent: {
    flex: 1,
    justifyContent: 'center',
    gap: 22,
  },
  back: {
    alignSelf: 'flex-start',
    paddingVertical: 50,
  },
  back2: {
    alignSelf: 'flex-start',
    paddingVertical: 10,
  },
  screenCentered: {
    flex: 1,
    padding: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: appColors.background,
    gap: 12,
  },
  title: {
    fontSize: 38,
    fontWeight: '700',
    color: appColors.textPrimary,
    letterSpacing: 4,
    textTransform: 'uppercase',
    padding: 10,
    paddingVertical: 20,
    fontFamily: 'Inter_700Bold',
  },
  title2: {
    fontSize: 25,
    fontWeight: '700',
    color: appColors.textPrimary,
    letterSpacing: 2,
    textTransform: 'uppercase',
    padding: 10,
    paddingVertical: 20,
    fontFamily: 'Inter_700Bold',
  },
  subtitle: {
    fontSize: 14,
    color: appColors.textSecondary,
    letterSpacing: 1,
    fontFamily: 'Inter_400Regular',
  },
  subtitle2: {
    fontSize: 6,
    color: appColors.textSecondary,
    letterSpacing: 1,
    fontFamily: 'Inter_400Regular',
  },
  subtitleCentered: {
    fontSize: 14,
    color: appColors.textSecondary,
    textAlign: 'center',
    letterSpacing: 1,
    fontFamily: 'Inter_400Regular',
  },
  input: {
    alignSelf: 'stretch',
    borderWidth: 1,
    borderColor: appColors.border,
    borderRadius: radii.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: appColors.textPrimary,
    backgroundColor: appColors.surface,
    letterSpacing: 0.5,
    fontFamily: 'Inter_400Regular',
  },
  primaryButton: {
    alignSelf: 'center',
    backgroundColor: appColors.primary,
    paddingVertical: 16,
    paddingHorizontal: 60,
    borderRadius: radii.full,
    marginTop: 8,
  },
  primaryButton2: {
    alignSelf: 'center',
    backgroundColor: appColors.primary,
    paddingVertical: 14,
    paddingHorizontal: 60,
    borderRadius: radii.full,
    marginTop: 8,
  },
  primaryButtonText: {
    color: appColors.primaryText,
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontFamily: 'Inter_600SemiBold',
  },
  secondaryButton: {
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: appColors.border,
    backgroundColor: 'transparent',
    paddingVertical: 14,
    paddingHorizontal: 60,
    borderRadius: radii.full,
  },
  secondaryButtonText: {
    color: appColors.textPrimary,
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 14,
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontFamily: 'Inter_400Regular',
  },
  errorText: {
    color: appColors.error,
    fontSize: 12,
    letterSpacing: 0.5,
    fontFamily: 'Inter_400Regular',
  },
});

export const useAppStyles = () => {
  const { colors } = useTheme();
  return StyleSheet.create({
    forgotText: { color: colors.textSecondary, textAlign: 'center', fontSize: 14, letterSpacing: 0.5, fontFamily: 'Inter_400Regular' },
    screen: { flex: 1, paddingHorizontal: 28, paddingVertical: 12, backgroundColor: colors.background, gap: 22 },
    screenContent: { flex: 1, justifyContent: 'center', gap: 22 },
    back: { alignSelf: 'flex-start', paddingVertical: 50 },
    back2: { alignSelf: 'flex-start', paddingVertical: 10 },
    screenCentered: { flex: 1, padding: 28, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background, gap: 12 },
    title: { fontSize: 38, fontWeight: '700', color: colors.textPrimary, letterSpacing: 4, textTransform: 'uppercase', padding: 10, paddingVertical: 20, fontFamily: 'Inter_700Bold' },
    subtitle: { fontSize: 14, color: colors.textSecondary, letterSpacing: 1, fontFamily: 'Inter_400Regular' },
    subtitleCentered: { fontSize: 14, color: colors.textSecondary, textAlign: 'center', letterSpacing: 1, fontFamily: 'Inter_400Regular' },
    input: { alignSelf: 'stretch', borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, paddingHorizontal: 16, paddingVertical: 14, fontSize: 15, color: colors.textPrimary, backgroundColor: colors.surface, letterSpacing: 0.5, fontFamily: 'Inter_400Regular' },
    primaryButton: { alignSelf: 'stretch', backgroundColor: colors.primary, paddingVertical: 16, borderRadius: radii.full, marginTop: 8 },
    primaryButton2: { alignSelf: 'center', backgroundColor: colors.primary, paddingVertical: 14, paddingHorizontal: 60, borderRadius: radii.full, marginTop: 8 },
    primaryButtonText: { color: colors.primaryText, textAlign: 'center', fontWeight: '600', fontSize: 14, letterSpacing: 2, textTransform: 'uppercase', fontFamily: 'Inter_600SemiBold' },
    secondaryButton: { alignSelf: 'center', borderWidth: 1, borderColor: colors.border, backgroundColor: 'transparent', paddingVertical: 14, paddingHorizontal: 60, borderRadius: radii.full },
    secondaryButtonText: { color: colors.textPrimary, textAlign: 'center', fontWeight: '400', fontSize: 14, letterSpacing: 2, textTransform: 'uppercase', fontFamily: 'Inter_400Regular' },
    errorText: { color: colors.error, fontSize: 12, letterSpacing: 0.5, fontFamily: 'Inter_400Regular' },
  });
};
